FROM node:20 AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npx nx build frontend

FROM nginx:alpine

COPY --from=builder /app/apps/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
